vehicles = [
    {
        "make": "Tesla",
        "model": "Model Y",
        "year": 2023,
        "price": 5899900,  # $58,999.00 → store as cents
        "bodyType": "SUV",
        "transmission": "Automatic",
        "fuelType": "Electric",
        "fuelConsumptionUrban": None,
        "fuelConsumptionExtraUrban": None,
        "fuelConsumptionCombined": None,
        "engineCapacity": None,
        "cylinders": None,
        "odometer": 1500,
        "driveType": "AWD",
        "doors": 5,
        "seats": 5,
        "color": "Pearl White",
        "rego": "TES123",
        "vin": "5YJYGDEE7LF123456",
        "stockNumber": "TS-001",
        "images": [
            "https://example.com/tesla-model-y-1.jpg",
            "https://example.com/tesla-model-y-2.jpg",
        ],
        "description": "The Tesla Model Y is a compact electric SUV with long range, fast acceleration, and advanced safety features.",
        "status": "Available",
        "condition": "New",
        "features": ["Autopilot", "Panoramic Glass Roof", "Heated Seats"],
        "viewsCount": 0,
    },
    {
        "make": "Ford",
        "model": "Mustang Mach-E",
        "year": 2022,
        "price": 4999900,
        "bodyType": "SUV",
        "transmission": "Automatic",
        "fuelType": "Electric",
        "fuelConsumptionUrban": None,
        "fuelConsumptionExtraUrban": None,
        "fuelConsumptionCombined": None,
        "engineCapacity": None,
        "cylinders": None,
        "odometer": 5000,
        "driveType": "RWD",
        "doors": 5,
        "seats": 5,
        "color": "Rapid Red",
        "rego": "FOR456",
        "vin": "3FMTK1RM5MMA12345",
        "stockNumber": "FR-002",
        "images": [
            "https://example.com/ford-mach-e-1.jpg",
            "https://example.com/ford-mach-e-2.jpg",
        ],
        "description": "The Ford Mustang Mach-E is an all-electric SUV that delivers spirited performance with zero emissions.",
        "status": "Available",
        "condition": "Used",
        "features": ["Adaptive Cruise Control", "Wireless Charging", "B&O Sound System"],
        "viewsCount": 0,
    },
    {
        "make": "Toyota",
        "model": "Corolla Hybrid",
        "year": 2021,
        "price": 2799900,
        "bodyType": "Sedan",
        "transmission": "Automatic",
        "fuelType": "Hybrid",
        "fuelConsumptionUrban": 3.5,
        "fuelConsumptionExtraUrban": 4.0,
        "fuelConsumptionCombined": 3.8,
        "engineCapacity": 1.8,
        "cylinders": 4,
        "odometer": 12000,
        "driveType": "FWD",
        "doors": 4,
        "seats": 5,
        "color": "Glacier White",
        "rego": "TOY789",
        "vin": "JTDBAMDE40J012345",
        "stockNumber": "TY-003",
        "images": [
            "https://example.com/toyota-corolla-1.jpg",
            "https://example.com/toyota-corolla-2.jpg",
        ],
        "description": "The Toyota Corolla Hybrid combines fuel efficiency with practicality, making it perfect for daily commuting.",
        "status": "Available",
        "condition": "Used",
        "features": ["Lane Keep Assist", "Apple CarPlay", "Reversing Camera"],
        "viewsCount": 0,
    },
    {
        "make": "Hyundai",
        "model": "Ioniq 5",
        "year": 2023,
        "price": 7199900,
        "bodyType": "SUV",
        "transmission": "Automatic",
        "fuelType": "Electric",
        "fuelConsumptionUrban": None,
        "fuelConsumptionExtraUrban": None,
        "fuelConsumptionCombined": None,
        "engineCapacity": None,
        "cylinders": None,
        "odometer": 2000,
        "driveType": "AWD",
        "doors": 5,
        "seats": 5,
        "color": "Digital Teal",
        "rego": "HYU321",
        "vin": "KM8KNDAF7PU123456",
        "stockNumber": "HY-004",
        "images": [
            "https://example.com/hyundai-ioniq5-1.jpg",
            "https://example.com/hyundai-ioniq5-2.jpg",
        ],
        "description": "The Hyundai Ioniq 5 is a revolutionary EV with ultra-fast charging, futuristic design, and spacious interior.",
        "status": "Available",
        "condition": "New",
        "features": ["Augmented Reality Head-Up Display", "Solar Roof", "V2L Charging"],
        "viewsCount": 0,
    },
    {
        "make": "Mazda",
        "model": "CX-5",
        "year": 2020,
        "price": 3599900,
        "bodyType": "SUV",
        "transmission": "Automatic",
        "fuelType": "Petrol",
        "fuelConsumptionUrban": 8.2,
        "fuelConsumptionExtraUrban": 6.9,
        "fuelConsumptionCombined": 7.5,
        "engineCapacity": 2.5,
        "cylinders": 4,
        "odometer": 35000,
        "driveType": "AWD",
        "doors": 5,
        "seats": 5,
        "color": "Machine Grey",
        "rego": "MAZ654",
        "vin": "JM0KF4WLA00312345",
        "stockNumber": "MZ-005",
        "images": [
            "https://example.com/mazda-cx5-1.jpg",
            "https://example.com/mazda-cx5-2.jpg",
        ],
        "description": "The Mazda CX-5 is a stylish, fuel-efficient SUV with a premium interior and sporty performance.",
        "status": "Available",
        "condition": "Used",
        "features": ["Blind Spot Monitoring", "Adaptive Headlights", "Leather Seats"],
        "viewsCount": 0,
    }
]

activities = [
    {
        "userId": "user1",
        "action": "viewed",
        "carTitles": ["Tesla Model Y"],
        "query": None,
        "timestamp": "2025-05-10T10:30:00Z",
    },
    {
        "userId": "user1",
        "action": "searched",
        "carTitles": [],
        "query": "electric SUV",
        "timestamp": "2025-05-10T10:45:00Z",
    },
    {
        "userId": "user2",
        "action": "compared",
        "carTitles": ["Tesla Model Y", "Ford Mustang Mach-E", "Hyundai Ioniq 5"],
        "query": None,
        "timestamp": "2025-05-10T11:00:00Z",
    },
    {
        "userId": "user3",
        "action": "saved",
        "carTitles": ["Ford Mustang Mach-E"],
        "query": None,
        "timestamp": "2025-05-10T11:30:00Z",
    },
    {
        "userId": "user2",
        "action": "searched",
        "carTitles": [],
        "query": "hybrid sedan under $30k",
        "timestamp": "2025-05-10T12:00:00Z",
    },
    {
        "userId": "user1",
        "action": "viewed",
        "carTitles": ["Hyundai Ioniq 5"],
        "query": None,
        "timestamp": "2025-05-10T12:15:00Z",
    },
]

# Sample preference data based on the Prisma model
preferences = [
    {
        "id": "pref1",
        "userId": "user1",
        "budgetMin": 20000.0,
        "budgetMax": 50000.0,
        "carTypes": ["SUV", "Sedan"],
        "fuelTypes": ["Electric", "Hybrid"],
        "brand": ["Tesla", "Toyota"],
        "features": ["Panoramic Glass Roof", "Heated Seats", "Autopilot"],
        "primarilyUse": ["Daily commute", "Family trips"],
        "topPriorities": ["Fuel efficiency", "Safety"],
        "updatedAt": "2025-05-10T08:00:00Z"
    },
    {
        "id": "pref2",
        "userId": "user2",
        "budgetMin": 30000.0,
        "budgetMax": 70000.0,
        "carTypes": ["SUV"],
        "fuelTypes": ["Electric", "Petrol"],
        "brand": ["Ford", "Hyundai"],
        "features": ["Adaptive Cruise Control", "Wireless Charging"],
        "primarilyUse": ["Road trips", "Weekend driving"],
        "topPriorities": ["Performance", "Comfort"],
        "updatedAt": "2025-05-09T10:30:00Z"
    },
    {
        "id": "pref3",
        "userId": "user3",
        "budgetMin": None,
        "budgetMax": None,
        "carTypes": ["Sedan", "Hatchback"],
        "fuelTypes": ["Hybrid"],
        "brand": ["Toyota", "Honda"],
        "features": ["Apple CarPlay", "Reversing Camera"],
        "primarilyUse": ["Daily commute"],
        "topPriorities": ["Reliability", "Fuel efficiency"],
        "updatedAt": "2025-05-08T15:45:00Z"
    }
]